prefirst/appefirst/urls.py
from django.urls import path
from appefirst import views
from django.conf.urls.static import static
from django.conf import settings



app_name = 'appefirst'
urlpatterns = [
    path('', views.MainPageView.as_view(), name='index'),
    path('dbd', views.DBDView.as_view(), name='dbd'),
    path('prod/<int:id>', views.ProductView.as_view(), name='prod_det'),
    path('domains', views.DomainsView.as_view(), name='domains'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prefirst/prefirst/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('appefirst.urls', namespace='appefirst')),
    path('login/',
         auth_views.LoginView.as_view(template_name='appefirst/login.html'),
         name='login'),
    path('logout/',
         auth_views.LogoutView.as_view(template_name='appefirst/logout.html'),
         name='logout'),
]

prefirst/appefirst/models.py
from django.db import models

# Create your models here.


PAGE_TYPE_CHOICES = [
    ('lp', 'landing'),
    ('pre', 'prelanding'),
    ('off', 'official'),
    ('oth', 'other'),
]

DOMAINS_OWNERS = [
    ('affbay', "affbay"),
    ('zenia', "zenia"),
    ('natalia', "natalia"),
    ('user1', "user1"),
    ('user2', "user2"),
    ('user3', "user3"),
]

class Country(models.Model):
    country_name = models.CharField(max_length=64, unique=True)
    country_code = models.CharField(max_length=3, unique=True)

    def __str__(self):
        return self.country_name

    class Meta:
        ordering = ['country_name']

class Products(models.Model):
    product_name = models.CharField(max_length=64)
    product_country = models.ForeignKey(Country, on_delete=models.PROTECT)
    product_price = models.IntegerField()
    product_epic = models.CharField(max_length=64)
    product_sku = models.CharField(max_length= 200, unique=True)
    product_desc = models.CharField(max_length=300)
    product_is_active = models.BooleanField(default=True)
    product_is_test = models.BooleanField(default=True)
    product_is_sell = models.BooleanField(default=True)
    product_is_smth = models.BooleanField(default=True)
    product_notes = models.CharField(max_length=300, default=None)

    class Meta:
        ordering = ['product_name']

    def __str__(self):
        return "{} {}".format(self.product_name, self.product_country)

class Pages(models.Model):
    page_type = models.CharField(choices=PAGE_TYPE_CHOICES, max_length=30)
    page_number = models.CharField(max_length=10, unique=False)
    page_code = models.CharField(max_length=64)
    page_url = models.CharField(max_length=300)
    page_product = models.ForeignKey(Products, on_delete=models.PROTECT)
    page_project_code = models.CharField(max_length=64)
    page_is_finished = models.BooleanField(default=False)
    page_is_in_affbay = models.BooleanField(default=False)
    page_is_smth1 = models.BooleanField(default=False)
    page_is_smth2 = models.BooleanField(default=False)
    page_notes1 = models.CharField(max_length=200, default=None)
    page_notes2 = models.CharField(max_length=200, default=None)

class Domains(models.Model):
    domain_name = models.CharField(max_length=64, default=None)
    domain_token = models.CharField(max_length=64, default=None, blank=True)
    domain_owner = models.CharField(choices=DOMAINS_OWNERS, max_length=30)

    def __str__(self):
        return "{}   owner:{}".format(self.domain_name, self.domain_owner)

class LottoNumbers(models.Model):
    draw_date = models.CharField(max_length=20)
    draw_number = models.CharField(max_length=20)
    number_1 = models.CharField(max_length=2, default='0')
    number_2 = models.CharField(max_length=2, default='0')
    number_3 = models.CharField(max_length=2, default='0')
    number_4 = models.CharField(max_length=2, default='0')
    number_5 = models.CharField(max_length=2, default='0')
    number_6 = models.CharField(max_length=2, default='0')

    def __str__(self):
        return "Data: {}, numery: {}, {}, {}, {}, {}, {}".format(self.draw_date, self.number_1, self.number_2, self.number_3, self.number_4, self.number_5, self.number_6)

prefirst/appefirst/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views import View
from appefirst import models
from xml.etree import ElementTree
import feedparser
import requests



class MainPageView(LoginRequiredMixin, View):
    def get(self, request):
        country = models.Country.objects.all()
        ctx = {"country": country}
        return render(request, 'appefirst/index.html', ctx)

class DBDView(LoginRequiredMixin, View):
    def get(self, request):
        url = 'http://serwis.mobilotto.pl/mapi_v6/index.php?json=getLotto'
        req = requests.get(url).json()
        num_losowania = req['num_losowania']
        numerki_tosort = req['numerki']
        numery_order = numerki_tosort.split(',')
        numerki_tosort = []
        for i in numery_order:
            if int(i)<10:
                i = "0"+i
            numerki_tosort.append(i)
        data_losowania_raw = req['data_losowania']
        cut = data_losowania_raw.split(' ')
        data_losowania = cut[0]
        numerki = sorted(numerki_tosort)
        print(numerki)
        rekord_z_data=models.LottoNumbers.objects.filter(draw_date=data_losowania)
        print(rekord_z_data)
        if not rekord_z_data:
            models.LottoNumbers.objects.create(
                draw_date=data_losowania,
                draw_number=num_losowania,
                number_1=numerki[0],
                number_2=numerki[1],
                number_3=numerki[2],
                number_4=numerki[3],
                number_5=numerki[4],
                number_6=numerki[5]
            )
        print('------------')
        print(request.is_ajax())
        print()

        url2 = 'https://www.tvn24.pl/najnowsze.xml'
        news = requests.get(url2)
        feeds = feedparser.parse('https://www.tvn24.pl/najnowsze.xml')
        news_title=[]
        news_href=[]
        for j in feeds.entries:
            news_title.append(j.title)
            news_href.append(j.links[0]['href'])
        ctx = { 'new1_title': news_title[0],
                'new2_title': news_title[1],
                'new3_title': news_title[2],
                'new4_title': news_title[3],
                'new5_title': news_title[4],
                'new6_title': news_title[5],
                'new1_href': news_href[0],
                'new2_href': news_href[2],
                'new3_href': news_href[3],
                'new4_href': news_href[4],
                'new5_href': news_href[5],
                'new6_href': news_href[6],
                'numerki': ','.join(numerki),
                'num_losowania': num_losowania,
                'data_losowania': data_losowania,
                'request': request.user
               }
        return render(request, 'appefirst/dbd.html', ctx)

    def post(self, request):
        return render(request, 'appefirst/dbd.html')


class ProductView(LoginRequiredMixin, View):
    def get(self, request, id):
        product = models.Products.objects.get(id=id)
        domain = "http://healthy-now-nature.com/"
        ctx = {"prod": product,
               "domain": domain}
        return render(request, 'appefirst/prod_det.html', ctx)


class DomainsView(LoginRequiredMixin, View):
    def get(self, request):
        domains_distinct = models.Domains.objects.all().distinct('domain_owner')
        domains = models.Domains.objects.all()
        ctx = {"domains": domains,
               "domains_distinct": domains_distinct}
        return render(request, 'appefirst/domains.html', ctx)

prefirst/appefirst/templates/appefirst/base.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Travel &mdash; 100% Free Fully Responsive HTML5 Template by FREEHTML5.co</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Template by FREEHTML5.CO" />
	<meta name="keywords" content="free html5, free template, free bootstrap, html5, css3, mobile first, responsive" />
	<meta name="author" content="FREEHTML5.CO" />
		<link rel="stylesheet" type="text/css" href="{% static 'appefirst/css/style.css' %}">


  <!--
	//////////////////////////////////////////////////////

	FREE HTML5 TEMPLATE
	DESIGNED & DEVELOPED by FREEHTML5.CO

	Website: 		http://freehtml5.co/
	Email: 			info@freehtml5.co
	Twitter: 		http://twitter.com/fh5co
	Facebook: 		https://www.facebook.com/fh5co

	//////////////////////////////////////////////////////
	 -->

  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="favicon.ico">

	<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>

	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'appefirst/css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'appefirst/css/icomoon.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'appefirst/css/bootstrap.css' %}">
	<!-- Superfish -->
	<link rel="stylesheet" href="{% static 'appefirst/css/superfish.css' %}">
	<!-- Magnific Popup -->
	<link rel="stylesheet" href="{% static 'appefirst/css/magnific-popup.css' %}">
	<!-- Date Picker -->
	<link rel="stylesheet" href="{% static 'appefirst/css/bootstrap-datepicker.min.css' %}">
	<!-- CS Select -->
	<link rel="stylesheet" href="{% static 'appefirst/css/cs-select.css' %}">
	<link rel="stylesheet" href="{% static 'appefirst/css/cs-skin-border.css' %}">

	<link rel="stylesheet" href="{% static 'appefirst/css/style.css' %}">


	<!-- Modernizr JS -->
	<script src="{% static 'appefirst/js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{% static 'appefirst/js/respond.min.js' %}"></script>
	<![endif]-->

	</head>
	<body>
			<header id="fh5co-header-section" class="sticky-banner">
			<div class="container">
				<div class="nav-header">
					<a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle dark"><i></i></a>
					<h1 id="fh5co-logo"><a href="{% url 'appefirst:index'%}">EFIRST</a></h1>
					<!-- START #fh5co-menu-wrap -->
					<nav id="fh5co-menu-wrap" role="navigation">
						<ul class="sf-menu" id="fh5co-primary-menu">
							<li class="active"><a href="{% url 'appefirst:index'%}">Home</a></li>
							<li><a href="{% url 'appefirst:domains'%}">Domains</a></li>
							{% if user.is_authenticated %}
							<li><a href="{% url 'logout' %}"">Wyloguj:</a></li>
							<li><a href="contact.html">{{ request.user }}</a></li>
							{% else %}
							<li><a href="{% url 'login' %}">Login</a></li>
							{% endif %}
						</ul>
					</nav>
				</div>
			</div>
		</header>

<div class="wrapper">
        {% block content %}
        {% endblock %}
</div>


</body>
</html>

prefirst/appefirst/templates/appefirst/dbd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>Numer losowania: {{num_losowania}}</div>
<div>Data losowania: {{data_losowania}}</div>
<div>Numery: {{numerki}}</div>

<form method="post">
    <div><input type="date" name="tile"></div>
    <div><input type="text" name="content"></div>
    <input type="submit" value="Wyślij">
</form>
{{ request }}

{{ news }}

</body>
</html>

prefirst/appefirst/templates/appefirst/domains.html
{% extends 'appefirst/base.html' %}
{% load static %}

{% block content %}

		<div id="fh5co-wrapper">
		<div id="fh5co-page">



		<!-- end:header-top -->

		<div class="fh5co-hero">
			<div class="fh5co-overlay"></div>
			<div class="fh5co-cover" data-stellar-background-ratio="0.5" style="background-image: url({% static 'appefirst/images/cover_bg_1.jpg' %});">
				<div class="desc">
					<div class="container">
						<div class="row">
							<div class="col-sm-2 col-md-2">
							</div>
							<div class="col-sm-8 col-md-8">
								<div class="tabulation animate-box">

								  <!-- Nav tabs -->
								   <ul class="nav nav-tabs" role="tablist">
									   {% for owner in domains_distinct %}
								      <li role="presentation" class="">
								      	<a href="#{{ owner.domain_owner }}" aria-controls="{{ owner.domain_owner }}" role="tab" data-toggle="tab">{{ owner.domain_owner }}</a>
								      </li>
									   {% endfor %}

								   </ul>

								   <!-- Tab panes -->
									<div class="tab-content">
										{% for domain in domains %}
									 <div role="tabpanel" class="tab-pane" id="{{ domain.domain_owner }}">
										<ul>
											<li>>{{ domain.domain_name }}</li>
											{% endfor %}
										</ul>


									 </div>






									</div>

								</div>
							</div>
							<div class="col-sm-2 col-md-2">
							</div>
							<div class="desc2 animate-box">

							</div>
						</div>
					</div>
				</div>
			</div>

		</div>




				</div>
			</div>
		</div>




				</div>
			</div>
		</div>




		</div>
	</div>
		<footer>
			<div id="footer">
				<div class="container">
					<div class="row row-bottom-padded-md">
						<div class="col-md-2 col-sm-2 col-xs-12 fh5co-footer-link">
							<h3>About Travel</h3>
							<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
						</div>
						<div class="col-md-2 col-sm-2 col-xs-12 fh5co-footer-link">
							<h3>Top Flights Routes</h3>
							<ul>
								<li><a href="#">Manila flights</a></li>
								<li><a href="#">Dubai flights</a></li>
								<li><a href="#">Bangkok flights</a></li>
								<li><a href="#">Tokyo Flight</a></li>
								<li><a href="#">New York Flights</a></li>
							</ul>
						</div>
						<div class="col-md-2 col-sm-2 col-xs-12 fh5co-footer-link">
							<h3>Top Hotels</h3>
							<ul>
								<li><a href="#">Boracay Hotel</a></li>
								<li><a href="#">Dubai Hotel</a></li>
								<li><a href="#">Singapore Hotel</a></li>
								<li><a href="#">Manila Hotel</a></li>
							</ul>
						</div>
						<div class="col-md-2 col-sm-2 col-xs-12 fh5co-footer-link">
							<h3>Interest</h3>
							<ul>
								<li><a href="#">Beaches</a></li>
								<li><a href="#">Family Travel</a></li>
								<li><a href="#">Budget Travel</a></li>
								<li><a href="#">Food &amp; Drink</a></li>
								<li><a href="#">Honeymoon and Romance</a></li>
							</ul>
						</div>
						<div class="col-md-2 col-sm-2 col-xs-12 fh5co-footer-link">
							<h3>Best Places</h3>
							<ul>
								<li><a href="#">Boracay Beach</a></li>
								<li><a href="#">Dubai</a></li>
								<li><a href="#">Singapore</a></li>
								<li><a href="#">Hongkong</a></li>
							</ul>
						</div>
						<div class="col-md-2 col-sm-2 col-xs-12 fh5co-footer-link">
							<h3>Affordable</h3>
							<ul>
								<li><a href="#">Food &amp; Drink</a></li>
								<li><a href="#">Fare Flights</a></li>
							</ul>
						</div>
					</div>
					<div class="row">
						<div class="col-md-6 col-md-offset-3 text-center">
							<p class="fh5co-social-icons">
								<a href="#"><i class="icon-twitter2"></i></a>
								<a href="#"><i class="icon-facebook2"></i></a>
								<a href="#"><i class="icon-instagram"></i></a>
								<a href="#"><i class="icon-dribbble2"></i></a>
								<a href="#"><i class="icon-youtube"></i></a>
							</p>
							<p>Copyright 2016 Free Html5 <a href="#">Module</a>. All Rights Reserved. <br>Made with <i class="icon-heart3"></i> by <a href="http://freehtml5.co/" target="_blank">Freehtml5.co</a> / Demo Images: <a href="https://unsplash.com/" target="_blank">Unsplash</a></p>
						</div>
					</div>
				</div>
			</div>
		</footer>



	</div>
	<!-- END fh5co-page -->

	</div>
	<!-- END fh5co-wrapper -->

	<!-- jQuery -->


	<script src="{% static 'appefirst/js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'appefirst/js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'appefirst/js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'appefirst/js/jquery.waypoints.min.js' %}"></script>
	<script src="{% static 'appefirst/js/sticky.js' %}"></script>

	<!-- Stellar -->
	<script src="{% static 'appefirst/js/jquery.stellar.min.js' %}"></script>
	<!-- Superfish -->
	<script src="{% static 'appefirst/js/hoverIntent.js' %}"></script>
	<script src="{% static 'appefirst/js/superfish.js' %}"></script>
	<!-- Magnific Popup -->
	<script src="{% static 'appefirst/js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'appefirst/js/magnific-popup-options.js' %}"></script>
	<!-- Date Picker -->
	<script src="{% static 'appefirst/js/bootstrap-datepicker.min.js' %}"></script>
	<!-- CS Select -->
	<script src="{% static 'appefirst/js/classie.js' %}"></script>
	<script src="{% static 'appefirst/js/selectFx.js' %}"></script>

	<!-- Main JS -->
	<script src="{% static 'appefirst/js/main.js' %}"></script>


{% endblock %}

prefirst/appefirst/templates/appefirst/index1.html
{% extends 'appefirst/base.html' %}
{% csrf_token %}
{% block content %}
    <div class="wrapper">

    {% if user.is_authenticated %}


      <div class="flex">
      {% for con in content %}

          <div class="dropdown">
        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ con.country_name}}
        </a>


        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          {% for i in con.products_set.all %}
          <a class="dropdown-item" href="#">{{ i.product_name }}</a>
{% endfor %}
        </div>

      </div>

      {% endfor %}

  </div>
    </div>



    {% else %}

    <h2>Bardzo nam przykro - nasza aplikacja jest przeznaczona tylko dla osób, które posiadają login i hasło</h2>

{% endif %}

    </div>

      <!-- --------------------------- -->


{% endblock content %}

prefirst/appefirst/templates/appefirst/login.html
{% extends 'appefirst/base.html' %}
{% load static %}
{% block content %}





		<div id="fh5co-wrapper">
		<div id="fh5co-page">



		<!-- end:header-top -->

		<div class="fh5co-hero">
			<div class="fh5co-overlay"></div>
			<div class="fh5co-cover" data-stellar-background-ratio="0.5" style="background-image: url({% static 'appefirst/images/cover_bg_1.jpg' %});">
				<div class="desc">
					<div class="container">
						<div class="row">
							<div class="col-sm-2 col-md-2">
							</div>
							<div class="col-sm-8 col-md-8">
								<div class="tabulation animate-box">

								  <!-- Nav tabs -->
								   <ul class="nav nav-tabs" role="tablist">
									   {% for countr in country %}
								      <li role="presentation" class="">
								      	<a href="#{{ countr.country_name }}" aria-controls="{{ countr.country_name }}" role="tab" data-toggle="tab">{{ countr.country_name }}</a>
								      </li>
									   {% endfor %}

								   </ul>

								   <!-- Tab panes -->
									<div class="tab-content text-center">
    <form method="post" action="{% url 'login' %}">
                {% csrf_token %}
        <p class="login_form">{{ form.as_p }}</p>
        <input class="submit btn btn-primary" type="submit" value="Zaloguj">
    </form>
    <div class="reg">
        <div class="text-info">
    <p>Nie masz konta? - zgłoś się do administratora</p>

    </div>





									</div>

								</div>
							</div>
							<div class="col-sm-2 col-md-2">
							</div>
							<div class="desc2 animate-box">

							</div>
						</div>
					</div>
				</div>
			</div>

		</div>



	<script src="{% static 'appefirst/js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'appefirst/js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'appefirst/js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'appefirst/js/jquery.waypoints.min.js' %}"></script>
	<script src="{% static 'appefirst/js/sticky.js' %}"></script>

	<!-- Stellar -->
	<script src="{% static 'appefirst/js/jquery.stellar.min.js' %}"></script>
	<!-- Superfish -->
	<script src="{% static 'appefirst/js/hoverIntent.js' %}"></script>
	<script src="{% static 'appefirst/js/superfish.js' %}"></script>
	<!-- Magnific Popup -->
	<script src="{% static 'appefirst/js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'appefirst/js/magnific-popup-options.js' %}"></script>
	<!-- Date Picker -->
	<script src="{% static 'appefirst/js/bootstrap-datepicker.min.js' %}"></script>
	<!-- CS Select -->
	<script src="{% static 'appefirst/js/classie.js' %}"></script>
	<script src="{% static 'appefirst/js/selectFx.js' %}"></script>

	<!-- Main JS -->
	<script src="{% static 'appefirst/js/main.js' %}"></script>


{% endblock %}

prefirst/appefirst/templates/appefirst/logout.html
{% extends 'appefirst/base.html' %}
{% load static %}
{% block content %}





		<div id="fh5co-wrapper">
		<div id="fh5co-page">



		<!-- end:header-top -->

		<div class="fh5co-hero">
			<div class="fh5co-overlay"></div>
			<div class="fh5co-cover" data-stellar-background-ratio="0.5" style="background-image: url({% static 'appefirst/images/cover_bg_1.jpg' %});">
				<div class="desc">
					<div class="container">
						<div class="row">
							<div class="col-sm-2 col-md-2">
							</div>
							<div class="col-sm-8 col-md-8">
								<div class="tabulation animate-box">

								  <!-- Nav tabs -->
								   <ul class="nav nav-tabs" role="tablist">
									   {% for countr in country %}
								      <li role="presentation" class="">
								      	<a href="#{{ countr.country_name }}" aria-controls="{{ countr.country_name }}" role="tab" data-toggle="tab">{{ countr.country_name }}</a>
								      </li>
									   {% endfor %}

								   </ul>

								   <!-- Tab panes -->
									<div class="tab-content text-center">
    <p class="text-capitalize">Wylogowałeś się prawidłowo</p>
    <div class="border-top pt-3">

            <a href="{% url 'login' %}" class="btn btn-primary">Log in Again</a>

<div class="text-info">
    <p class="text-capitalize">Życzymy miłego dnia i do zobaczenia wkrótce</p>

    </div>





									</div>

								</div>
							</div>
							<div class="col-sm-2 col-md-2">
							</div>
							<div class="desc2 animate-box">

							</div>
						</div>
					</div>
				</div>
			</div>

		</div>



	<script src="{% static 'appefirst/js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'appefirst/js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'appefirst/js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'appefirst/js/jquery.waypoints.min.js' %}"></script>
	<script src="{% static 'appefirst/js/sticky.js' %}"></script>

	<!-- Stellar -->
	<script src="{% static 'appefirst/js/jquery.stellar.min.js' %}"></script>
	<!-- Superfish -->
	<script src="{% static 'appefirst/js/hoverIntent.js' %}"></script>
	<script src="{% static 'appefirst/js/superfish.js' %}"></script>
	<!-- Magnific Popup -->
	<script src="{% static 'appefirst/js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'appefirst/js/magnific-popup-options.js' %}"></script>
	<!-- Date Picker -->
	<script src="{% static 'appefirst/js/bootstrap-datepicker.min.js' %}"></script>
	<!-- CS Select -->
	<script src="{% static 'appefirst/js/classie.js' %}"></script>
	<script src="{% static 'appefirst/js/selectFx.js' %}"></script>

	<!-- Main JS -->
	<script src="{% static 'appefirst/js/main.js' %}"></script>


{% endblock %}